paths:
  /reviews/oauth:
    get:
      responses:
        '200':
          description: 200 OK
      operationId: review.oauth
      summary: Oauth trigger API
      security:
        - clientIdHeader: []
  /reviews/comment:
    post:
      responses:
        '200':
          description: 200 OK
  /reviews/list:
    get:
      responses:
        '200':
          description: 200 OK
      parameters:
        - $ref: '#/parameters/itemId'
      security:
        - clientIdHeader: []
  /reviews/post:
    post:
      tags:
        - review
      operationId: review.post
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
definitions: {}
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: socialreview
  version: 1.0.0
  title: socialreview
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apic-oauth-provider:
    type: oauth2
    description: OAuth 2.0 authorization
    flow: implicit
    authorizationUrl: >-
      https://api.us.apiconnect.ibmcloud.com/centusibmcom-cloudnative-dev/bluecompute/oauth20/authorize
    scopes:
      review: Allow user to pose comment/reviews to Social review API
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - apic-oauth-provider:
      - review
    clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(TARGET_HOST)$(request.path)$(request.search)
          tls-profile: ''
  properties:
    TARGET_HOST:
      value: >-
        https://apiconnect-a21c2f57-212c-4aca-9b16-ce3e649ce4f4.centusibmcom-cloudnative-dev.apic.mybluemix.net
      description: ''
      encoded: false
  gateway: datapower-gateway
parameters:
  itemId:
    name: itemId
    type: integer
    required: false
    in: query
    format: int32
